// Canonical Louisiana municipality names for the City typeahead on the
// Post-a-task form (and reusable anywhere a clean city string matters —
// browse filters, signup location, parish analytics).
//
// Why a static list: Helpr operates only in Louisiana, so the city
// universe is small and finite. A bundled list (≈5KB) gives instant,
// offline, zero-cost autocomplete and — critically — guarantees a
// consistent canonical spelling for the one address part shown
// publicly on every job card. No Google/Mapbox Places API needed.
//
// The list is a curated set covering essentially all of Louisiana's
// population. The City field stays a free-text combobox, so any tiny
// unincorporated community not listed here can still be typed.
//
// Parish is intentionally NOT stored here — it drives Louisiana sales
// tax and is resolved authoritatively from ZIP via the
// get_parish_for_zip RPC (see src/lib/parishLookup.ts). Keeping parish
// out of this hand-maintained list avoids a tax-accuracy liability.

export const LOUISIANA_CITIES: string[] = [
  "Abbeville",
  "Abita Springs",
  "Addis",
  "Albany",
  "Alexandria",
  "Amite City",
  "Arabi",
  "Baker",
  "Ball",
  "Bastrop",
  "Baton Rouge",
  "Bayou Cane",
  "Belle Chasse",
  "Bernice",
  "Berwick",
  "Blanchard",
  "Bogalusa",
  "Bossier City",
  "Boutte",
  "Breaux Bridge",
  "Bridge City",
  "Broussard",
  "Brusly",
  "Bunkie",
  "Carencro",
  "Central",
  "Chalmette",
  "Church Point",
  "Clinton",
  "Columbia",
  "Coushatta",
  "Covington",
  "Crowley",
  "Cut Off",
  "Denham Springs",
  "DeQuincy",
  "DeRidder",
  "Destrehan",
  "Donaldsonville",
  "Erath",
  "Estelle",
  "Eunice",
  "Farmerville",
  "Ferriday",
  "Franklin",
  "Franklinton",
  "Galliano",
  "Geismar",
  "Golden Meadow",
  "Gonzales",
  "Gramercy",
  "Gray",
  "Greenwell Springs",
  "Gretna",
  "Hammond",
  "Harahan",
  "Harvey",
  "Haughton",
  "Houma",
  "Independence",
  "Iowa",
  "Jackson",
  "Jeanerette",
  "Jefferson",
  "Jena",
  "Jennings",
  "Jonesboro",
  "Kaplan",
  "Kenner",
  "Kentwood",
  "Kinder",
  "Lacombe",
  "Lafayette",
  "Lake Charles",
  "Laplace",
  "Larose",
  "Lockport",
  "Luling",
  "Mandeville",
  "Mansfield",
  "Many",
  "Marksville",
  "Marrero",
  "Mathews",
  "Meraux",
  "Metairie",
  "Minden",
  "Monroe",
  "Morgan City",
  "Napoleonville",
  "Natchitoches",
  "New Iberia",
  "New Orleans",
  "New Roads",
  "Norco",
  "Oakdale",
  "Oberlin",
  "Opelousas",
  "Patterson",
  "Pearl River",
  "Pineville",
  "Plaquemine",
  "Ponchatoula",
  "Port Allen",
  "Port Sulphur",
  "Prairieville",
  "Raceland",
  "Rayne",
  "Rayville",
  "Reserve",
  "Ruston",
  "Scott",
  "Shreveport",
  "Slidell",
  "Sorrento",
  "Springhill",
  "St. Francisville",
  "St. Gabriel",
  "St. Martinville",
  "St. Rose",
  "Sulphur",
  "Tallulah",
  "Terrytown",
  "Thibodaux",
  "Vidalia",
  "Ville Platte",
  "Vinton",
  "Violet",
  "Vivian",
  "Walker",
  "Welsh",
  "West Monroe",
  "Westlake",
  "Westwego",
  "Winnfield",
  "Winnsboro",
  "Youngsville",
  "Zachary",
];
