project_id = "steigdwrpkosbiycshwz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.complete-signup]
    verify_jwt = false
  [functions.send-account-status-email]
    verify_jwt = false
