// The opt-out. Every commercial email in the product points here.
//
// ═════════════════════════════════════════════════════════════════════════
// THE PATH, HOP BY HOP
//
//   1. A commercial template renders <MarketingFooter unsubscribeUrl={…}>.
//      The sender built that URL with `buildUnsubscribeUrl(recipientEmail)`
//      (_shared/unsubscribe.ts): the address, base64url-encoded, plus an
//      HMAC-SHA256 signature over `unsub.v1:<address>`.
//   2. The same sender sets `List-Unsubscribe: <that URL>, <mailto:…>` and
//      `List-Unsubscribe-Post: List-Unsubscribe=One-Click`, so Gmail and
//      Apple Mail render their own native unsubscribe control.
//   3a. NATIVE CONTROL → the mail client POSTs `List-Unsubscribe=One-Click`
//       to this function. No session, no page, no confirmation step. RFC 8058
//       requires the unsubscribe to take effect on that POST alone.
//   3b. FOOTER LINK → the recipient GETs this function. It takes effect on
//       that single click too, and then renders a confirmation page with a
//       one-button "resubscribe" in case the click was an accident or a
//       corporate link-scanner followed it.
//   4. This handler verifies the signature, resolves the address to a
//      profile, and writes the two reversible consent flags:
//          profiles.marketing_consent                -> false
//          notification_preferences.email_promotions -> false
//   5. Every commercial sender re-reads both flags before its next send:
//        • send-marketing-blast  — filters on both, FAIL-CLOSED on a read error
//        • engagement-automations (welcome drip, win-back) — same
//      So an opt-out generated by the digest stops the campaigns too. There
//      is no per-campaign opt-out, by design: the statute's opt-out is from
//      the sender's commercial mail, not from one message.
//
// ═════════════════════════════════════════════════════════════════════════
// WHAT THIS DELIBERATELY DOES NOT TOUCH: `suppressed_emails`
//
// That table is the HARD suppression list — hard bounces and spam complaints,
// written only by `resend-webhook`, append-only, permanent. It is read by the
// TRANSACTIONAL senders as well (send-notification-email fails closed on it;
// engagement-automations aborts its whole run if it cannot read it).
//
// So writing a commercial opt-out there would ALSO kill the recipient's
// payout notifications, job updates, password resets and security notices.
// That is not what "unsubscribe from these emails" asks for, and CAN-SPAM's
// opt-out right does not extend to transactional mail (§7702(17) puts
// transactional/relationship messages outside the commercial definition
// entirely). Two lists, two meanings:
//
//     suppressed_emails         hard, permanent, ALL mail   (bounce/complaint)
//     marketing_consent +       soft, reversible, COMMERCIAL only
//       email_promotions
//
// If you ever find yourself adding a `suppressed_emails` insert to this file,
// you are about to silence someone's escrow-release email. Don't.
//
// ═════════════════════════════════════════════════════════════════════════
// DEPLOYMENT
//
//   supabase/config.toml needs
//       [functions.email-unsubscribe]
//         verify_jwt = false
//   because a mail client's one-click POST carries no Supabase JWT, and a
//   recipient clicking the footer link is by definition not signed in.
//   Authenticity is the HMAC in the token, checked below.
//
//   Signing key: EMAIL_UNSUBSCRIBE_SECRET, falling back to CRON_SECRET (the
//   key `email-tracking` already signs with). With neither set this function
//   answers 503 and the footers fall back to the preferences page — loudly,
//   never silently.

import { createClient } from 'npm:@supabase/supabase-js@2'
import { corsHeadersFull as corsHeaders } from '../_shared/cors.ts'
import { htmlEscape } from '../_shared/safe-strings.ts'
import { getAppUrl } from '../_shared/appUrl.ts'
import { LOGO_URL } from '../_shared/email-templates/styles.ts'
import { SUPPORT_EMAIL } from '../_shared/resend.ts'
import { unsubscribeSigningConfigured, verifyUnsubscribeToken } from '../_shared/unsubscribe.ts'

/**
 * PostgREST turns `*` into `%` and passes `%`/`_` straight into SQL ILIKE, so
 * an address containing an underscore (`john_doe@…` — extremely common) would
 * match the wrong row. Escape the three pattern characters before the
 * case-insensitive lookup.
 */
function escapeLikePattern(value: string): string {
  return value.replace(/[\\%_*]/g, (c) => `\\${c}`)
}

/**
 * Resolve an address to a profile.
 *
 * Exact match first — signup lowercases, so that is the overwhelming case —
 * then a case-insensitive fallback for rows written before that, or by an
 * admin typing mixed case.
 */
async function findProfile(
  // deno-lint-ignore no-explicit-any
  supabase: any,
  email: string,
): Promise<{ user_id: string } | null> {
  const exact = await supabase
    .from('profiles')
    .select('user_id')
    .eq('email', email)
    .limit(1)
    .maybeSingle()
  // The error is checked, never assumed away: a failed read here would
  // otherwise look identical to "this address has no account" and the
  // opt-out would be silently dropped.
  if (exact.error) throw new Error(`profile lookup failed: ${exact.error.message}`)
  if (exact.data) return exact.data

  const ci = await supabase
    .from('profiles')
    .select('user_id')
    .ilike('email', escapeLikePattern(email))
    .limit(1)
    .maybeSingle()
  if (ci.error) throw new Error(`profile lookup failed: ${ci.error.message}`)
  return ci.data ?? null
}

/**
 * Flip both consent flags for one user.
 *
 * `optOut = true` unsubscribes, `false` resubscribes. Returns nothing and
 * THROWS on failure — the caller must never report success for a write that
 * did not happen, which is the whole failure mode this endpoint exists to fix.
 *
 * `.select('user_id')` on the profiles UPDATE is deliberate: an UPDATE that
 * matches zero rows resolves `{ data: [], error: null }`, so without it a
 * user_id that no longer exists would report a successful opt-out.
 */
async function setCommercialConsent(
  // deno-lint-ignore no-explicit-any
  supabase: any,
  userId: string,
  optOut: boolean,
): Promise<void> {
  const { data: updated, error: profileError } = await supabase
    .from('profiles')
    .update({ marketing_consent: !optOut })
    .eq('user_id', userId)
    .select('user_id')
  if (profileError) throw new Error(`marketing_consent write failed: ${profileError.message}`)
  if (!updated || updated.length === 0) {
    throw new Error('marketing_consent write matched no profile row')
  }

  // Upsert, not update: `notification_preferences` rows are created lazily by
  // the app, so a user who never opened the notifications tab has no row and
  // a bare UPDATE would match zero rows and report success. `user_id` is
  // UNIQUE (migration 20260312023604), which is what makes onConflict work.
  const { error: prefsError } = await supabase
    .from('notification_preferences')
    .upsert({ user_id: userId, email_promotions: !optOut }, { onConflict: 'user_id' })
  if (prefsError) throw new Error(`email_promotions write failed: ${prefsError.message}`)
}

const PAGE_CSS = `
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 24px 16px;
    background: #F0F2F4; color: #23231A;
    font: 16px/1.6 'Montserrat', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    display: flex; justify-content: center;
  }
  .card {
    width: 100%; max-width: 520px; background: #ffffff;
    border: 1px solid #CBCFD8; border-radius: 14px; padding: 32px 28px;
  }
  img.logo { display: block; width: 80px; height: auto; margin: 0 0 24px; border: 0; }
  h1 { font-size: 22px; line-height: 1.3; margin: 0 0 12px; color: #23231A; }
  p { margin: 0 0 16px; color: #55656D; }
  .addr { font-weight: 600; color: #23231A; overflow-wrap: anywhere; }
  button {
    appearance: none; border: 0; cursor: pointer;
    background: #5E6544; color: #fff; font: inherit; font-weight: 600;
    border-radius: 12px; padding: 14px 28px;
  }
  a { color: #984216; }
  .fine { font-size: 13px; color: #6E7C83; margin: 24px 0 0; }
  @media (prefers-color-scheme: dark) {
    body { background: #1A1B15; color: #F0F2F4; }
    .card { background: #23231A; border-color: #3A3B30; }
    h1, .addr { color: #F0F2F4; }
    p { color: #C3C9CC; }
  }
`

/** Minimal branded page. Every interpolated value goes through htmlEscape. */
function page(title: string, bodyHtml: string, status = 200): Response {
  return new Response(
    `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${htmlEscape(title)} · Louisiana Helpr</title>
<style>${PAGE_CSS}</style></head>
<body><main class="card">
<img class="logo" src="${LOGO_URL}" alt="Louisiana Helpr">
${bodyHtml}
</main></body></html>`,
    {
      status,
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/html; charset=utf-8',
        // Never let a proxy cache an opt-out result page keyed on a token.
        'Cache-Control': 'no-store',
        'X-Robots-Tag': 'noindex, nofollow',
      },
    },
  )
}

function text(body: string, status: number): Response {
  return new Response(body, {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
  })
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders })
  if (req.method !== 'GET' && req.method !== 'POST') {
    return text('Method not allowed', 405)
  }

  const url = new URL(req.url)

  // A one-click POST from a mail client carries `List-Unsubscribe=One-Click`
  // as a form body; the confirmation page's resubscribe button posts
  // `action=resubscribe`. Anything else is treated as an unsubscribe.
  let action = 'unsubscribe'
  if (req.method === 'POST') {
    try {
      const body = await req.text()
      if (new URLSearchParams(body).get('action') === 'resubscribe') action = 'resubscribe'
    } catch {
      // An unreadable body is still a valid one-click unsubscribe.
    }
  }

  if (!unsubscribeSigningConfigured()) {
    // 503, not a friendly "you're unsubscribed": telling someone their opt-out
    // worked when nothing was written is the exact defect this replaces.
    console.error('[email-unsubscribe] no EMAIL_UNSUBSCRIBE_SECRET or CRON_SECRET configured')
    return req.method === 'POST'
      ? text('Unsubscribe temporarily unavailable', 503)
      : page(
          'Something went wrong',
          `<h1>We couldn't process that right now</h1>
           <p>Our unsubscribe service is temporarily unavailable. Please email
           <a href="mailto:${htmlEscape(SUPPORT_EMAIL)}">${htmlEscape(SUPPORT_EMAIL)}</a>
           and we'll take you off the list by hand.</p>`,
          503,
        )
  }

  const email = await verifyUnsubscribeToken(url.searchParams.get('e'), url.searchParams.get('sig'))
  if (!email) {
    return req.method === 'POST'
      ? text('Invalid or expired unsubscribe link', 400)
      : page(
          'Link not valid',
          `<h1>That unsubscribe link isn't valid</h1>
           <p>It may have been altered in transit, or it may be from an email sent before
           our signing key changed.</p>
           <p>You can turn promotional email off yourself under
           <a href="${htmlEscape(getAppUrl())}/profile?tab=notifications">Notifications</a> in your
           profile, or email <a href="mailto:${htmlEscape(SUPPORT_EMAIL)}">${htmlEscape(SUPPORT_EMAIL)}</a>
           and we'll do it for you.</p>`,
          400,
        )
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    (Deno.env.get('SECRET_KEY') ?? Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'))!,
  )

  let profile: { user_id: string } | null
  try {
    profile = await findProfile(supabase, email)
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    console.error('[email-unsubscribe]', message)
    return req.method === 'POST'
      ? text('Unsubscribe failed, please retry', 500)
      : page(
          'Something went wrong',
          `<h1>We couldn't process that right now</h1>
           <p>Please try the link again in a minute, or email
           <a href="mailto:${htmlEscape(SUPPORT_EMAIL)}">${htmlEscape(SUPPORT_EMAIL)}</a>.</p>`,
          500,
        )
  }

  if (!profile) {
    // No account for this address. Every commercial segment in the product is
    // built by querying `profiles`, so there is nothing that could mail it
    // again and nothing to write. Reported as success rather than "unknown
    // address" so this endpoint cannot be used to test whether an address has
    // a Helpr account.
    //
    // Note this is the one gap: an address that is NOT a Helpr account can
    // only ever have received a `test_email` preview from the blast tool,
    // which an admin addresses by hand. It is deliberately not written to
    // `suppressed_emails` — that list is permanent and would block the
    // verification email if this person later signed up.
    console.warn('[email-unsubscribe] no profile for a validly signed address — nothing to write')
  } else {
    try {
      await setCommercialConsent(supabase, profile.user_id, action !== 'resubscribe')
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      console.error('[email-unsubscribe]', message)
      return req.method === 'POST'
        ? text('Unsubscribe failed, please retry', 500)
        : page(
            'Something went wrong',
            `<h1>We couldn't save that</h1>
             <p>Please try the link again in a minute, or email
             <a href="mailto:${htmlEscape(SUPPORT_EMAIL)}">${htmlEscape(SUPPORT_EMAIL)}</a>
             and we'll take you off the list by hand.</p>`,
            500,
          )
    }
  }

  console.log(`[email-unsubscribe] ${action} recorded`, { hasProfile: !!profile, method: req.method })

  // RFC 8058: the one-click POST answers 200 with no body the client shows.
  if (req.method === 'POST') {
    return text(action === 'resubscribe' ? 'Resubscribed' : 'Unsubscribed', 200)
  }

  const safeEmail = htmlEscape(email)
  const tokenQuery = `e=${encodeURIComponent(url.searchParams.get('e') ?? '')}&sig=${encodeURIComponent(url.searchParams.get('sig') ?? '')}`

  if (action === 'resubscribe') {
    return page(
      "You're back on the list",
      `<h1>You're subscribed again</h1>
       <p><span class="addr">${safeEmail}</span> will receive Louisiana Helpr news and
       promotional email again.</p>
       <p class="fine">Changed your mind? Manage this any time under Notifications in your
       <a href="${htmlEscape(getAppUrl())}/profile?tab=notifications">profile</a>.</p>`,
    )
  }

  return page(
    "You're unsubscribed",
    `<h1>You're unsubscribed</h1>
     <p>We've removed <span class="addr">${safeEmail}</span> from Louisiana Helpr promotional
     email. This takes effect immediately — you won't get another campaign, welcome series or
     win-back message.</p>
     <p>You'll still receive email about your account: job updates, payments and payouts,
     security notices and password resets. You can turn those off individually under
     Notifications in your
     <a href="${htmlEscape(getAppUrl())}/profile?tab=notifications">profile</a>.</p>
     <form method="post" action="?${tokenQuery}">
       <input type="hidden" name="action" value="resubscribe">
       <button type="submit">Actually, resubscribe me</button>
     </form>
     <p class="fine">Questions? <a href="mailto:${htmlEscape(SUPPORT_EMAIL)}">${htmlEscape(SUPPORT_EMAIL)}</a></p>`,
  )
})
