import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newContext().then(c=>c.newPage());
await p.setViewportSize({width:393,height:852});
await p.goto("http://localhost:8096/jobs?job=891a13fc-2152-47d2-87ca-ff3068c6c7c8", { waitUntil:"networkidle" }).catch(()=>{});
await p.waitForTimeout(3500);
const d = await p.$('[role="dialog"]');
console.log("url:", p.url());
console.log("guest preview dialog opened:", !!d);
if (d) console.log("dialog:", (await d.innerText()).replace(/\s+/g," ").slice(0,220));
await b.close();
