import { chromium } from "playwright";
import { execSync } from "node:child_process";
const sess = JSON.parse(execSync("node scripts/test-signin-link.mjs helper --session --json").toString());
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 375, height: 812 } });
await ctx.addInitScript(([k, v]) => { localStorage.setItem(k, v); localStorage.setItem("helpr_onboarding", JSON.stringify({ completed: true, currentStep: 0, completedSteps: [] })); }, [sess.key, sess.value]);
const page = await ctx.newPage();
await page.goto("http://localhost:4205/admin?view=people", { waitUntil: "networkidle" }); await page.waitForTimeout(1200);
await page.locator("[role=tab]").filter({ hasText: /^All/ }).first().click(); await page.waitForTimeout(600);
await page.getByPlaceholder(/Search name/).fill("Perry"); await page.waitForTimeout(800);
await page.locator("[role=button]").filter({ hasText: /Perry/ }).first().click(); await page.waitForTimeout(1200);
const tabs = await page.locator("[role=dialog] [role=tab]").evaluateAll((els) => els.map((e) => ({ t: e.textContent.trim(), sw: e.scrollWidth, cw: e.clientWidth, textW: Math.round(e.firstChild ? (() => { const r = document.createRange(); r.selectNodeContents(e); return r.getBoundingClientRect().width; })() : 0) })));
console.log(JSON.stringify(tabs));
await page.locator("[role=dialog] [role=tab]").filter({ hasText: "Overview" }).click(); await page.waitForTimeout(500);
await page.screenshot({ path: "shots/fix-user-tabs-375.png", clip: { x: 0, y: 60, width: 375, height: 260 } });
await page.goto("http://localhost:4205/admin?view=home", { waitUntil: "networkidle" }); await page.waitForTimeout(1500);
console.log((await page.locator("main").first().innerText()).match(/\$[\d.]+\s*Payments Collected[^\n]*/g));
await page.goto("http://localhost:4205/admin?view=analytics", { waitUntil: "networkidle" }); await page.waitForTimeout(2500);
console.log((await page.locator("main").first().innerText()).match(/\$[\d.]+\s*Payments Collected[^\n]*/g));
await b.close();
