#!/usr/bin/env node
/**
 * audit-surface — enumerate the app's ACTUAL auditable surface.
 *
 * WHY: a previous audit pass walked routes and reported coverage, but missed
 * "a ton of dialog screens and other paths". Routes are roughly a quarter of
 * the real surface: the app has ~49 routes but ~86 components that render an
 * overlay, plus tab and view variants. An agent that walks routes and stops
 * has audited a fraction of the app while sounding complete.
 *
 * This script produces the authoritative checklist every audit lane must cover
 * and report against. Regenerate it, don't hand-maintain it.
 *
 *   node scripts/audit-surface.mjs           # write docs/audit/launch-2026-09/SURFACE.md
 *   node scripts/audit-surface.mjs --json
 */
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const OUT_DIR = join(ROOT, "docs/audit/launch-2026-09");

function walk(dir, acc = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, acc);
    else if (/\.tsx?$/.test(e) && !/\.test\.tsx?$/.test(e)) acc.push(p);
  }
  return acc;
}

const files = walk(SRC);
const rel = (p) => relative(ROOT, p);

// --- routes -----------------------------------------------------------------
const app = readFileSync(join(SRC, "App.tsx"), "utf8");
const routes = [...app.matchAll(/<Route\s+path="([^"]+)"/g)].map((m) => m[1]);
const redirects = new Set(
  [...app.matchAll(/<Route\s+path="([^"]+)"[^>]*(?:Navigate|Redirect)/g)].map((m) => m[1]),
);

// --- tab / view variants ----------------------------------------------------
const tabs = new Set();
const views = new Set();
for (const f of files) {
  const s = readFileSync(f, "utf8");
  for (const m of s.matchAll(/[?&]tab=([a-zA-Z_][\w-]*)/g)) tabs.add(m[1]);
  for (const m of s.matchAll(/[?&]view=([a-zA-Z_][\w-]*)/g)) views.add(m[1]);
}

// --- overlays: anything that renders a Dialog/Sheet/Drawer/Popover ----------
const OVERLAY_TAG = /<(Dialog|AlertDialog|Sheet|Drawer|Popover|HoverCard|DropdownMenu|ContextMenu)\b/;
const overlays = [];
for (const f of files) {
  if (rel(f).startsWith("src/components/ui/")) continue; // primitives, not surfaces
  const s = readFileSync(f, "utf8");
  if (!OVERLAY_TAG.test(s)) continue;
  const kinds = new Set(
    [...s.matchAll(/<(Dialog|AlertDialog|Sheet|Drawer|Popover|HoverCard|DropdownMenu|ContextMenu)\b/g)].map((m) => m[1]),
  );
  overlays.push({ file: rel(f), kinds: [...kinds].sort() });
}

// --- multi-step flows: components with a step/stage state machine -----------
const flows = files
  .filter((f) => {
    const s = readFileSync(f, "utf8");
    // Steps are compared against BOTH numbers and string literals in this repo
    // (step === 1, but also step === "checkout" / "form" / "entry" / "confirmation").
    // An earlier version only matched digits and reported 0 flows, which was wrong.
    return /\b(step|stage|currentStep|activeStep|phase)\s*===?\s*(\d+|["'][a-z_-]+["'])/i.test(s);
  })
  .map(rel);

const surface = {
  routes: routes.filter((r) => !redirects.has(r)),
  redirects: [...redirects],
  tabs: [...tabs].sort(),
  views: [...views].sort(),
  overlays: overlays.sort((a, b) => a.file.localeCompare(b.file)),
  flows: flows.sort(),
};

if (process.argv.includes("--json")) {
  console.log(JSON.stringify(surface, null, 2));
  process.exit(0);
}

const total =
  surface.routes.length + surface.tabs.length + surface.views.length + surface.overlays.length;

const L = [];
L.push("# Auditable surface — the coverage checklist");
L.push("");
L.push("_Generated by `node scripts/audit-surface.mjs`. Do not hand-edit._");
L.push("");
L.push("**Routes are roughly a quarter of the surface.** A previous audit walked routes,");
L.push("reported coverage, and missed a large number of dialogs and sub-paths. Every lane");
L.push("reports coverage against THIS file, not against the route list.");
L.push("");
L.push(`| Surface class | Count |`);
L.push(`|---|---|`);
L.push(`| Routes (non-redirect) | ${surface.routes.length} |`);
L.push(`| Redirect-only routes | ${surface.redirects.length} |`);
L.push(`| \`?tab=\` variants | ${surface.tabs.length} |`);
L.push(`| \`?view=\` variants | ${surface.views.length} |`);
L.push(`| Overlay-rendering components | ${surface.overlays.length} |`);
L.push(`| Multi-step flows | ${surface.flows.length} |`);
L.push(`| **Addressable surfaces** | **${total}** |`);
L.push("");
L.push("## Routes");
L.push("");
for (const r of surface.routes) L.push(`- [ ] \`${r}\``);
L.push("");
L.push("## Redirect-only routes (verify they land correctly, incl. query preservation)");
L.push("");
for (const r of surface.redirects) L.push(`- [ ] \`${r}\``);
L.push("");
L.push("## `?tab=` variants");
L.push("");
for (const t of surface.tabs) L.push(`- [ ] \`?tab=${t}\``);
L.push("");
L.push("## `?view=` variants");
L.push("");
for (const v of surface.views) L.push(`- [ ] \`?view=${v}\``);
L.push("");
L.push("## Overlays — dialogs, sheets, drawers, popovers, menus");
L.push("");
L.push("**This is the list that got missed last time.** Each must be OPENED and audited:");
L.push("measured against the viewport (the containing-block trap), keyboard-reachable,");
L.push("dismissible, and correct in every state.");
L.push("");
L.push("| Component | Overlay kinds |");
L.push("|---|---|");
for (const o of surface.overlays) L.push(`| \`${o.file}\` | ${o.kinds.join(", ")} |`);
L.push("");
L.push("## Multi-step flows (audit every step, and interruption at every step)");
L.push("");
for (const f of surface.flows) L.push(`- [ ] \`${f}\``);
L.push("");
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "SURFACE.md"), L.join("\n"));
console.log(`SURFACE.md written — ${total} addressable surfaces`);
console.log(`  routes ${surface.routes.length} · redirects ${surface.redirects.length} · tabs ${surface.tabs.length} · views ${surface.views.length} · overlays ${surface.overlays.length} · flows ${surface.flows.length}`);
