#!/usr/bin/env bash
# Land the current worktree's commits on main WITH the generated files current.
#
#   bash scripts/land.sh            # fetch, rebase, refresh, commit, verify, push
#   bash scripts/land.sh --dry-run  # everything except the push
#   bash scripts/land.sh --pr       # same, but land through a PR with auto-merge
#
# --pr (Q44): once main's protection is strict with enforce_admins, a direct
# push to main is refused. --pr pushes the same verified HEAD to the branch
# land/<current branch> (force: it is this worktree's own branch), opens a PR
# for it if none is open, and turns on auto-merge with REBASE (not squash: a
# squash rewrites the messages and drops per-commit Sensitive-Review trailers).
# Strict protection needs the branch up to date with main, so if main moves
# before the checks finish, re-run `bash scripts/land.sh --pr`: it rebases
# and force-pushes the branch again.
#
# Why (2026-09-27): agents land with `git push --no-verify origin HEAD:main`,
# which skips the pre-commit hook that regenerates the inventories. One new
# test file moved the guard count and main went red on check:generated
# (503fd193c: docs/GUARD-BURNDOWN.md 650 vs 651, docs/audit/vacuity-report.json
# 1195 vs 1196). The generated files depend on the REBASED tree, so they are
# refreshed after the rebase, then proven with check:generated before pushing.
#
# Commits ONLY what the refresh produced: tracked files must be clean to start
# (commit your work first; never git stash in this repo), and untracked files
# that already existed (e.g. docs/audit/morning/*.md) are never staged.
set -euo pipefail

DRY=0
PR=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --pr) PR=1 ;;
    *) echo "land: unknown argument $arg (use --dry-run, --pr)" >&2; exit 1 ;;
  esac
done

cd "$(git rev-parse --show-toplevel)"

if [ -d "$(git rev-parse --git-path rebase-merge)" ] || [ -d "$(git rev-parse --git-path rebase-apply)" ]; then
  echo "land: a rebase is in progress; finish it first (git status)." >&2
  exit 1
fi

DIRTY=$(git status --porcelain --untracked-files=no)
if [ -n "$DIRTY" ]; then
  echo "land: uncommitted tracked changes; commit them (or move them out) first:" >&2
  echo "$DIRTY" | sed 's/^/  /' >&2
  exit 1
fi

# Untracked files present before the refresh are someone else's; never staged.
UNTRACKED_BEFORE=$(git ls-files --others --exclude-standard | sort)

attempt=0
while :; do
  attempt=$((attempt + 1))
  git fetch -q origin main
  git rebase -q origin/main

  npm run -s inventories:refresh

  CHANGED=$( { git diff --name-only; comm -13 <(printf '%s\n' "$UNTRACKED_BEFORE") <(git ls-files --others --exclude-standard | sort); } | sed '/^$/d' | sort -u)
  if [ -n "$CHANGED" ]; then
    echo "land: generated files refreshed:"
    echo "$CHANGED" | sed 's/^/  /'
    echo "$CHANGED" | tr '\n' '\0' | xargs -0 git add --
    git commit -q --no-verify -m "chore: refresh generated inventories

Regenerated by scripts/land.sh after rebasing onto origin/main.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"
  else
    echo "land: generated files already current."
  fi

  # The same check CI runs; red here stops the push.
  npm run -s check:generated

  # A money/authz/data-model commit with no recorded review turns main red on
  # the "Sensitive review record" workflow (15921ea17, 2026-09-27). Check only
  # the commits this push adds; record the review first
  # (node scripts/check-sensitive-review.mjs record <sha> <reviewer> <verdict>).
  node scripts/check-sensitive-review.mjs --range origin/main..HEAD --strict

  # Exact-count bookkeeping guards. Every main Vitest red on 2026-09-30 (12 of
  # 12, runs 36740238457..36787599011) was one of these: a commit moved a
  # count (unused exports, markerless [~] items, a done-when marker, an
  # unmetered prod spec, the expiry inventory) and --no-verify skipped every
  # local check; 287ab11c2 then reached main red on the component-size one.
  # They take ~4s; run them on the rebased tree on every land.
  npx vitest run \
    src/test/deadcodeRatchet.test.ts \
    src/test/openPartlyDoneItemsSayDoneWhen.test.ts \
    src/test/requestBudget.test.ts \
    src/test/expiryMonitor.test.ts \
    src/test/componentSizeRatchet.test.ts

  # db-deploy runs the moment a migration reaches main, before CI's vitest
  # does. Its two commonest reds (ledger 00fd2bd0, runs since 2026-09-24:
  # 5x "types.ts matches the live schema", 3x "no allow check says yes to a
  # NULL argument"; newest 36361411866 / 36360932660 from the Q807 migration)
  # each have a repo-only vitest twin that was already red on that commit.
  # Run the twins here whenever the push touches migrations or their inputs.
  if git diff --name-only origin/main..HEAD | grep -qE '^(supabase/migrations/|scripts/ci/|src/integrations/supabase/types\.ts$)'; then
    npx vitest run src/test/typesCoverMigrationFunctions.test.ts src/test/nullArgNeverAllows.test.ts
  fi

  if [ "$DRY" = 1 ]; then
    echo "land: --dry-run, not pushing. HEAD $(git rev-parse --short HEAD)"
    exit 0
  fi

  if [ "$PR" = 1 ]; then
    BR="land/$(git rev-parse --abbrev-ref HEAD)"
    git push --no-verify --force origin "HEAD:refs/heads/$BR"
    if ! gh pr view "$BR" --json state --jq .state 2>/dev/null | grep -qx OPEN; then
      gh pr create --base main --head "$BR" --fill-first
    fi
    gh pr merge "$BR" --rebase --auto
    echo "land: $(git rev-parse --short HEAD) is on $BR with auto-merge on; it lands when the required checks pass."
    echo "land: if main moves first (strict protection), re-run bash scripts/land.sh --pr."
    exit 0
  fi

  if git push --no-verify origin HEAD:main; then
    echo "land: pushed $(git rev-parse --short HEAD) to main."
    exit 0
  fi
  if [ "$attempt" -ge 3 ]; then
    echo "land: push rejected $attempt times (main keeps moving); re-run." >&2
    exit 1
  fi
  echo "land: push rejected (main moved); fetching and rebasing again."
done
