#!/usr/bin/env bash
# Land the current worktree's commits on main WITH the generated files current.
#
#   bash scripts/land.sh            # fetch, rebase, refresh, commit, verify, push
#   bash scripts/land.sh --dry-run  # everything except the push
#
# Why (2026-09-27): agents land with `git push --no-verify origin HEAD:main`,
# which skips the pre-commit hook that regenerates the inventories. One new
# test file moved the guard count and main went red on check:generated
# (503fd193c: docs/GUARD-BURNDOWN.md 650 vs 651, docs/audit/vacuity-report.json
# 1195 vs 1196). The generated files depend on the REBASED tree, so they are
# refreshed after the rebase, then proven with check:generated before pushing.
#
# Commits ONLY what the refresh produced: tracked files must be clean to start
# (commit your work first; never git stash in this repo), and untracked files
# that already existed (e.g. docs/audit/morning/*.md) are never staged.
set -euo pipefail

DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

cd "$(git rev-parse --show-toplevel)"

if [ -d "$(git rev-parse --git-path rebase-merge)" ] || [ -d "$(git rev-parse --git-path rebase-apply)" ]; then
  echo "land: a rebase is in progress; finish it first (git status)." >&2
  exit 1
fi

DIRTY=$(git status --porcelain --untracked-files=no)
if [ -n "$DIRTY" ]; then
  echo "land: uncommitted tracked changes; commit them (or move them out) first:" >&2
  echo "$DIRTY" | sed 's/^/  /' >&2
  exit 1
fi

# Untracked files present before the refresh are someone else's; never staged.
UNTRACKED_BEFORE=$(git ls-files --others --exclude-standard | sort)

attempt=0
while :; do
  attempt=$((attempt + 1))
  git fetch -q origin main
  git rebase -q origin/main

  npm run -s inventories:refresh

  CHANGED=$( { git diff --name-only; comm -13 <(printf '%s\n' "$UNTRACKED_BEFORE") <(git ls-files --others --exclude-standard | sort); } | sed '/^$/d' | sort -u)
  if [ -n "$CHANGED" ]; then
    echo "land: generated files refreshed:"
    echo "$CHANGED" | sed 's/^/  /'
    echo "$CHANGED" | tr '\n' '\0' | xargs -0 git add --
    git commit -q --no-verify -m "chore: refresh generated inventories

Regenerated by scripts/land.sh after rebasing onto origin/main.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"
  else
    echo "land: generated files already current."
  fi

  # The same check CI runs; red here stops the push.
  npm run -s check:generated

  if [ "$DRY" = 1 ]; then
    echo "land: --dry-run, not pushing. HEAD $(git rev-parse --short HEAD)"
    exit 0
  fi

  if git push --no-verify origin HEAD:main; then
    echo "land: pushed $(git rev-parse --short HEAD) to main."
    exit 0
  fi
  if [ "$attempt" -ge 3 ]; then
    echo "land: push rejected $attempt times (main keeps moving); re-run." >&2
    exit 1
  fi
  echo "land: push rejected (main moved); fetching and rebasing again."
done
