-- Security advisor cleanup (2026-05-05): closes 74+ "security_definer_function_executable"
-- warnings by revoking EXECUTE on internal trigger functions from anon,
-- authenticated, and PUBLIC. Trigger functions fire via the row-change
-- mechanism — they do NOT need EXECUTE grants for the trigger itself to
-- work. Revoking only blocks the PostgREST `/rest/v1/rpc/<name>` callable
-- surface so anon/authenticated can't fire these directly.
--
-- Authoritative list (37 functions) generated by querying pg_proc for
-- functions with prosecdef=TRUE in `public` whose return type is `trigger`
-- or `event_trigger`. RPC functions (returning anything else) are
-- intentionally left alone to avoid breaking the SPA.
--
-- Storage bucket "Public read" policy cleanup is deferred — the existing
-- per-user/per-job policies already cover legitimate access, but dropping
-- the public-read policy could affect anon job-photo browsing depending on
-- the bucket's public flag. Needs separate analysis.

DO $$
DECLARE
  fn_name TEXT;
  trigger_fns TEXT[] := ARRAY[
    'add_owner_as_member',
    'audit_admin_job_status_change',
    'audit_role_changes',
    'auto_pending_credentials',
    'block_shadowbanned_applications',
    'check_referral_bonus',
    'enforce_application_limit',
    'enforce_business_member_limit',
    'enforce_business_seat_limit',
    'enforce_business_verification_safety',
    'enforce_job_status_transition',
    'enforce_message_rate',
    'enforce_open_job_limit',
    'enforce_parish_limit',
    'enforce_referral_cap',
    'enforce_review_validity',
    'enforce_saved_search_limit',
    'flag_suspicious_review',
    'handle_new_user',
    'log_verification_change',
    'notify_helper_on_direct_offer',
    'notify_helper_on_tip',
    'notify_helpers_on_job_post',
    'notify_on_application',
    'notify_on_job_update',
    'notify_on_payment_escrowed',
    'notify_poster_on_status_change',
    'notify_saved_searches_on_new_job',
    'prevent_admin_role_self_grant',
    'prevent_self_escalation',
    'rls_auto_enable',
    'scan_message_content',
    'set_dispute_deadline',
    'set_revision_deadline',
    'sync_email_verified',
    'sync_email_verified_on_insert',
    'track_revision_scope_creep'
  ];
BEGIN
  FOREACH fn_name IN ARRAY trigger_fns LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION public.%I() FROM PUBLIC', fn_name);
    EXECUTE format('REVOKE ALL ON FUNCTION public.%I() FROM anon', fn_name);
    EXECUTE format('REVOKE ALL ON FUNCTION public.%I() FROM authenticated', fn_name);
  END LOOP;
END $$;
