// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';
import { hydratePromise, keychainStorageAdapter } from './keychainStorageAdapter';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Hydrate native NSUserDefaults into cache before constructing the
// supabase client. Top-level await — Vite handles this on iOS WebKit.
if (Capacitor.isNativePlatform()) {
  await hydratePromise;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: Capacitor.isNativePlatform() ? keychainStorageAdapter : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
