/**
 * api/share.ts imports the build-time shell snapshot `scripts/generated/og-shell.js`
 * (gitignored; written by `npm run build` from dist/index.html). A fresh
 * checkout has none, and Vite's import analysis fails the whole test file on a
 * missing import before any `vi.mock` can stand in for it.
 *
 * So a test that imports the handler calls this first. It writes the snapshot
 * from dist/index.html (a real build's output) or, failing that, the source
 * index.html — only when none exists, atomically (write + rename), and it
 * NEVER deletes it: two test files in parallel workers used to create and then
 * remove the same file, and whichever removed it first broke the other's
 * import. A snapshot a real build left behind is used as-is, never overwritten;
 * the next `npm run build` replaces a test-written one.
 */
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

export function ensureOgShellSnapshot(root: string): void {
  const target = resolve(root, "scripts/generated/og-shell.js");
  if (existsSync(target)) return;
  const built = resolve(root, "dist/index.html");
  const html = readFileSync(existsSync(built) ? built : resolve(root, "index.html"), "utf8");
  mkdirSync(dirname(target), { recursive: true });
  const tmp = `${target}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;
  writeFileSync(
    tmp,
    "// GENERATED by src/test/helpers/ogShellSnapshot.ts (no build present); `npm run build` replaces it.\n" +
      `export const SHELL_HTML = ${JSON.stringify(html)};\n`,
  );
  renameSync(tmp, target);
}
