// Race-safe source walker for the source-text guard tests.
//
// Several guards (dropped columns, admin endpoint authz, audit catalogue,
// shared edge imports, the parity checks) work by walking the repo and reading
// every .ts/.tsx file. Two things make the naive version flaky, and both bit
// during the 2026-08-25/26 audit:
//
//  1. `src/test/edge/harness.ts` WRITES transient `*.gen.ts` modules into
//     `src/test/edge/` and removes them again when the suite finishes. A guard
//     that walks the tree in another worker can list one of those files and
//     then have it deleted before readFileSync opens it — ENOENT, and the
//     guard fails with an error that has nothing to do with what it guards.
//  2. Those generated modules are rewritten copies of edge functions. Scanning
//     them means a guard can report an "offender" that is a build artifact,
//     with a path that no longer exists by the time anyone reads the failure.
//
// Raising the timeout does not address either — the file is missing, not slow.
// So: skip generated modules, and treat a file that vanishes mid-walk as
// absent rather than fatal.
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const SKIP_DIRS = new Set(["node_modules", "dist", "coverage", ".git", "playwright-report", "test-results"]);
const EXTS = [".ts", ".tsx"];

/** Generated by the edge-function test harness; never real source. */
export const isGenerated = (file: string) => file.endsWith(".gen.ts");

/**
 * Every .ts/.tsx file under `roots`, excluding build output and the edge
 * harness's transient modules. Directories that disappear mid-walk are
 * skipped for the same reason files are.
 */
export function walkSource(roots: string[]): string[] {
  const out: string[] = [];
  const visit = (dir: string) => {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return; // removed while we were walking
    }
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry)) continue;
      const full = join(dir, entry);
      let isDir: boolean;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue; // vanished between readdir and stat
      }
      if (isDir) visit(full);
      else if (EXTS.some((e) => entry.endsWith(e)) && !isGenerated(full)) out.push(full);
    }
  };
  for (const root of roots) visit(root);
  return out;
}

/**
 * File contents, or `null` if it no longer exists. A guard should skip a null
 * rather than fail: the file is gone, so it cannot be an offender.
 */
export function readSource(file: string): string | null {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return null;
  }
}
